ismission13RyanPinkney/Components/TeamsViewComponent.cs
// Author Ryan Pinkney
// This is the models for the teams view component

using System;
using System.Linq;
using ismission13RyanPinkney.Models;
using Microsoft.AspNetCore.Mvc;

namespace ismission13RyanPinkney.Components
{
    // Inherit for the viewcomponent 
    public class TeamsViewComponent : ViewComponent
    {

        private IBowlersRepository repo { get; set; }

        // Set the contructor
        public TeamsViewComponent(IBowlersRepository temp)
        {
            repo = temp;
        }

        // Grab the information for the repository and decide whay will be returned to the view component
        public IViewComponentResult Invoke()
        {
            // Set the view bag
            ViewBag.SelectedType = RouteData?.Values["teamNames"];

            // Get the data
            var teams = repo.Teams
                .Select(x => x.TeamName)
                .Distinct()
                .OrderBy(x => x);


            // Return the team names
            return View(teams);
        }

    


    
 
    }
}

ismission13RyanPinkney/Controllers/HomeController.cs
// Author: Ryan Pinkney
// This is the home controller with the action routes


using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ismission13RyanPinkney.Models;
using Microsoft.EntityFrameworkCore;

namespace ismission13RyanPinkney.Controllers
{
    public class HomeController : Controller
    {
        // Repo
        private IBowlersRepository repo;

        public HomeController(IBowlersRepository temp)
        {
            repo = temp;
        }


        // Path for the index
        public IActionResult Index()
        {
            return View();
        }

        // Path to see all the bowlers
        public IActionResult List(string teamNames)
        {

            ViewBag.header = teamNames;

            // Get all the bowlers
            var BowlerList = repo.Bowlers
                .Where(p => p.Team.TeamName == teamNames || teamNames == null)
                .Include(x => x.Team)
                .ToList();

            return View(BowlerList);
        }


        // Route for the get bowler
        [HttpGet]
        public IActionResult Add()
        {

            // Fill the bag
            ViewBag.lstTeams = repo.Teams.ToList();

            return View();
        }

        // Route for the post bowler
        [HttpPost]
        public IActionResult Add(Bowler response)
        {
            // Check to see if the data inputed is valid
            if (!ModelState.IsValid)
            {
                // Load the bag
                ViewBag.lstTeams = repo.Teams.ToList();


                return View(response);
            }

            var oSingleTimeMax = repo.Bowlers.OrderByDescending(u => u.BowlerID).FirstOrDefault();


            response.BowlerID = oSingleTimeMax.BowlerID + 1;

            // Save the infomration to the database
            repo.CreateBowler(response);



            // Return them to the confirmation page
            return RedirectToAction("List");
        }



        // Route to edit get
        [HttpGet]
        public IActionResult Edit(int id)
        {
            // Load the bag
            ViewBag.lstTeams = repo.Teams.ToList();


            // Pull a single record
            var oSingleRecord = repo.Bowlers
            .Single(x => x.BowlerID == id);


            // Return the view with the single object
            return View(oSingleRecord);
        }

        // Route to edit post
        [HttpPost]
        public IActionResult Edit(Bowler b)
        {

            // Check to see if the data inputted was valid
            if (!ModelState.IsValid)
            {

                // Load the bag
                ViewBag.lstTeams = repo.Teams.ToList();

                // Return to waitlist
                return View(b);


            };

            // Save the infomration to the database
            repo.UpdateBowler(b);

            // Redirect to the movie list route
            return RedirectToAction("List");

        }


        // Route to Delete get
        [HttpGet]
        public IActionResult Delete(int id)
        {

            // Pull a single record
            var oSingleRecord = repo.Bowlers
            .Single(x => x.BowlerID == id);


            // Return the view with the single object
            return View(oSingleRecord);
        }

        // Route to delete post
        [HttpPost]
        public IActionResult Delete(Bowler b)
        {
            // Delete the record identifed by the id in the response
            repo.DeleteBowler(b);

            // Redirect to the movie list route
            return RedirectToAction("List");
        }






    }
}

ismission13RyanPinkney/Views/Home/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <!--Set the title-->
    ViewData["Title"] = "Add Bowler";
}

<!--
Author: Ryan Pinkney
Form page to add a person

-->


<h3>Enter a new bowler</h3>

<!--Bring in the model-->
@model Bowler

<div>

    <!--Form to add a movie to the database-->
    <form method="POST" class="text-center">

        <!--Field for first name-->
        <label asp-for="BowlerFirstName">First Name</label>
        <input asp-for="BowlerFirstName" /><br />

        <!--Field for last name-->
        <label asp-for="BowlerLastName">Last Name</label>
        <input asp-for="BowlerLastName" /><br />

        <!--Field for middle inital-->
        <label asp-for="BowlerMiddleInit">Middle Inital</label>
        <input asp-for="BowlerMiddleInit" /><br />

        <!--Field for address-->
        <label asp-for="BowlerAddress">Address</label>
        <input asp-for="BowlerAddress" /><br />

        <!--Field for city-->
        <label asp-for="BowlerCity">City</label>
        <input asp-for="BowlerCity" /><br />

        <!--Field for state-->
        <label asp-for="BowlerState">State</label>
        <input asp-for="BowlerState" /><br />

        <!--Field for zip-->
        <label asp-for="BowlerZip">Zip</label>
        <input asp-for="BowlerZip" /><br />

        <!--Field for phone-->
        <label asp-for="BowlerPhoneNumber">Phone</label>
        <input asp-for="BowlerPhoneNumber" /><br />


        <!--Field for teamid-->
        <label asp-for="TeamID">Team</label>
        <select asp-for="TeamID">

            <!--Load the team name from the database through the controller-->
            <option value="">Select a Team</option>

            @foreach (Team m in ViewBag.lstTeams)
            {
                <option value="@m.TeamID">@m.TeamName</option>

            }
        </select><br />

        <!--Field to submit-->
        <button type="submit">Submit</button>

        <!--Show the data validation message-->
        <div asp-validation-summary="All"></div>

    </form>

</div>

ismission13RyanPinkney/Views/Home/Delete.cshtml
<!---
Author: Ryan Pinkney
    This is the deletion confirmation page


-->
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <!-- Set the tab title-->
    ViewData["Title"] = "Delete Bowler";
}

@model Bowler

<!--Confirmation message-->
<h2>Confirm Deletion</h2>
<h3> Are you sure you want to delete @Model.BowlerFirstName @Model.BowlerLastName?</h3>

<!--Form to confirm deletion-->
<form asp-action="Delete" method="post">

    <!--Button to cancel-->
    <a asp-controller="Home" asp-action="List" class="btn btn-primary">Cancel</a>

    <!--button to delete-->
    <button type="submit">Delete</button>

    <!--Hide the movie id in the form-->
    <input type="hidden" asp-for="BowlerID" />
</form>

ismission13RyanPinkney/Views/Home/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <!--Set the title-->
    ViewData["Title"] = "Edit Bolwer";
}

<!--
Author: Ryan Pinkney
Edit a bowler record page

-->


<h3>Edit bowler record</h3>

<!--Bring in the model-->
@model Bowler

<div>

    <!--Form to add a movie to the database-->
    <form method="POST" class="text-center">


        <!--Hidden field for the bowler id-->
        <input type="hidden" asp-for="BowlerID" />

        <!--Field for first name-->
        <label asp-for="BowlerFirstName">First Name</label>
        <input asp-for="BowlerFirstName" /><br />

        <!--Field for last name-->
        <label asp-for="BowlerLastName">Last Name</label>
        <input asp-for="BowlerLastName" /><br />

        <!--Field for middle inital-->
        <label asp-for="BowlerMiddleInit">Middle Inital</label>
        <input asp-for="BowlerMiddleInit" /><br />

        <!--Field for address-->
        <label asp-for="BowlerAddress">Address</label>
        <input asp-for="BowlerAddress" /><br />

        <!--Field for city-->
        <label asp-for="BowlerCity">City</label>
        <input asp-for="BowlerCity" /><br />

        <!--Field for state-->
        <label asp-for="BowlerState">State</label>
        <input asp-for="BowlerState" /><br />

        <!--Field for zip-->
        <label asp-for="BowlerZip">Zip</label>
        <input asp-for="BowlerZip" /><br />

        <!--Field for phone-->
        <label asp-for="BowlerPhoneNumber">Phone</label>
        <input asp-for="BowlerPhoneNumber" /><br />


        <!--Field for teamid-->
        <label asp-for="TeamID">Team</label>
        <select asp-for="TeamID">

            <!--Load the team names from the database through the controller-->
            <option value="">Select a Team</option>

            @foreach (Team m in ViewBag.lstTeams)
            {
                <option value="@m.TeamID">@m.TeamName</option>

            }

        </select><br />

        <!--Field to submit-->
        <button type="submit">Submit</button>

        <!--Show the data validation message-->
        <div asp-validation-summary="All"></div>

    </form>

</div>

ismission13RyanPinkney/Views/Home/Index.cshtml
<!--Author Ryan Pinkney
This is the landing page
-->

@{
    <!-- Set the tab title-->
    ViewData["Title"] = "Home Page";
}

<!-- Title for the index-->
<div class="text-center">
    <h1 class="display-4">Bowling League from 402</h1>
    <p>This is the mission 13 assignment for Ryan Pinkney</p>
</div>

ismission13RyanPinkney/Views/Home/List.cshtml
<!-- Author Ryan Pinkney
    This page display the entire roster of the database
    -->


@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <!-- Set the tab title-->
    ViewData["Title"] = "All Bowlers";

}

<!-- Header that dynamically build the name of the team-->
<h2>Bowler Roster: <span style="color: green;">@ViewBag.header</span></h2>



<!--Retrieves the list from the controller-->
@model List<Bowler>
<!--Table to show all the applicants-->
<!--Display to display the records formatted with Bootstrap-->


<div class="row">
    <div class="col-3">
        <vc:teams></vc:teams>
    </div>


    <div class="col-9">
        <table class="table table-bordered table-striped">

            <thread class="font-weight-bold">

                <!--Columns-->
                <tr>
                    <td>First Name:</td>
                    <td>Last Name:</td>
                    <td>Middle Inital:</td>
                    <td>Address:</td>
                    <td>City:</td>
                    <td>State:</td>
                    <td>Zip:</td>
                    <td>Phone:</td>
                    <td>Team:</td>
                </tr>

            </thread>

            <tbody>

                <!--Rows-->
                @foreach (var iCount in Model)
                {<!-- Model needs to be capitalized-->

                    <tr>
                        <td>@iCount.BowlerFirstName</td>
                        <td>@iCount.BowlerLastName</td>
                        <td>@iCount.BowlerMiddleInit</td>
                        <td>@iCount.BowlerAddress</td>
                        <td>@iCount.BowlerCity</td>
                        <td>@iCount.BowlerState</td>
                        <td>@iCount.BowlerZip</td>
                        <td>@iCount.BowlerPhoneNumber</td>
                        <td>@iCount.Team.TeamName</td>

                        <!--Buttons to delete and edit that pass the id as a parameter in the url-->
                        <td><a asp-controller="Home" asp-action="Edit" asp-route-id="@iCount.BowlerID">Edit</a></td>
                        <td><a asp-controller="Home" asp-action="Delete" asp-route-id="@iCount.BowlerID">Delete</a></td>
                    </tr>

                }



            </tbody>


        </table>
    </div>
</div>